/* Generated By:JavaCC: Do not edit this line. WorkGrammarTreeConstants.java Version 5.0 */
package com.nwsuaf.rain;

public interface WorkGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTSENTENCEBLOCK = 2;
  public int JJTSENTENCE = 3;
  public int JJTSEQUENCESEN = 4;
  public int JJTDECLARESEN = 5;
  public int JJTASSIGMENTSEN = 6;
  public int JJTCONDITIONSEN = 7;
  public int JJTLOOPSENT = 8;
  public int JJTCONDITION = 9;
  public int JJTEXPRESSION = 10;
  public int JJTADDITIVEEXPRESSION = 11;
  public int JJTMULTIPLICATIVEEXPRESSION = 12;
  public int JJTUNARYEXPRESSION = 13;
  public int JJTIDENTIFIER = 14;
  public int JJTINTEGER = 15;
  public int JJTRELATIONS = 16;
  public int JJTRETURNSENT = 17;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "SentenceBlock",
    "Sentence",
    "SequenceSen",
    "DeclareSen",
    "AssigmentSen",
    "ConditionSen",
    "LoopSent",
    "Condition",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
    "Relations",
    "ReturnSent",
  };
}
/* JavaCC - OriginalChecksum=80c5c429cdca10f09705b87854e9edb3 (do not edit this line) */
